<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <AssemblyName>Flow.Launcher.Plugin.JevFileSearch</AssemblyName>
    <PackageId>Flow.Launcher.Plugin.JevFileSearch</PackageId>
    <Authors>ibnuh</Authors>
    <PackageProjectUrl>https://github.com/ibnuh/Flow.Launcher.Plugin.JevFileSearch</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ibnuh/Flow.Launcher.Plugin.JevFileSearch</RepositoryUrl>
    <PackageTags>flow-launcher flow-plugin</PackageTags>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <UseWpf>true</UseWpf>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>None</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="plugin.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Flow.Launcher.Plugin" Version="5.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="images\icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
